#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    s = input().strip()
    chars = {}
    
    for letter in s:
        chars[letter] = chars.get(letter, 0) + 1

    #sort alphabetically
    chars = {key: val for key, val in sorted(chars.items(), key = lambda x: x[0])}

    #sort by value
    chars = sorted(chars.items(), key=lambda x: x[1], reverse=True)

    for x in range(0, 3):
        item = chars[x]
        print(item[0],item[1])
