#!/bin/python3

import math
import os
import random
import re
import sys
import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    format = '%a %d %b %Y %X %z'
    date1 = datetime.datetime.strptime(t1, format)
    date2 = datetime.datetime.strptime(t2, format)
    result = abs(round((date1-date2).total_seconds()))
    return str(result)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta + '\n')

    fptr.close()
